from PyQt5.QtWidgets import QDialog, QLineEdit, QPushButton, QVBoxLayout, QLabel
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogIncident(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Параметры инцидента:"))
layout.addWidget(QLabel("Дата / Время (UTC):"))
self.datetime = QDateTimeEdit()
self.datetime.setDateTime(QDateTime.fromString("28 июня 2025 г.", "dd MMMM yyyy g."))
layout.addWidget(self.datetime)
layout.addWidget(QLabel("От кого:"))
self.from_ = QLineEdit("Капитан координатор")
layout.addWidget(self.from_)
layout.addWidget(QLabel("Кому:"))
self.to = QLineEdit("ОД МСКЦ (odmsrcc@mail.ru, od_msrcc@mail.morspas.com)")
layout.addWidget(self.to)
layout.addWidget(QLabel("Копия:"))
self.copy = QLineEdit()
layout.addWidget(self.copy)
layout.addWidget(QLabel("Дополнительно:"))
self.additional = QLineEdit()
layout.addWidget(self.additional)
btn_cancel = QPushButton("Отмена")
btn_cancel.clicked.connect(self.close)
layout.addWidget(btn_cancel)
btn_save = QPushButton("Сохранить PDF")
layout.addWidget(btn_save)
btn_send = QPushButton("Отправить")
layout.addWidget(btn_send)