from PyQt5.QtWidgets import QDialog, QDoubleSpinBox, QSpinBox, QPushButton, QVBoxLayout, QLabel
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogWeatherParams(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Расчет погоды:"))
layout.addWidget(QLabel("Ветер:"))
self.wind_speed = QDoubleSpinBox(minimum=0, value=1.0)
layout.addWidget(self.wind_speed)
layout.addWidget(QLabel("Направление (градусы):"))
self.wind_dir = QSpinBox(minimum=0, maximum=360, value=90)
layout.addWidget(self.wind_dir)
layout.addWidget(QLabel("Волны:"))
self.wave_height = QDoubleSpinBox(minimum=0, value=10.0)
layout.addWidget(self.wave_height)
layout.addWidget(QLabel("Температура воздуха °C:"))
self.air_temp = QDoubleSpinBox(minimum=-50, maximum=50, value=0.52)
layout.addWidget(self.air_temp)
layout.addWidget(QLabel("Температура воды °C:"))
self.water_temp = QDoubleSpinBox(minimum=-10, maximum=40, value=16.49)
layout.addWidget(self.water_temp)
layout.addWidget(QLabel("Источник информации:"))
self.source = QLineEdit()
layout.addWidget(self.source)
layout.addWidget(QLabel("Начало действия UTC:"))
self.start_time = QDateTimeEdit()
self.start_time.setDateTime(QDateTime.fromString("02.52", "hh.mm"))
layout.addWidget(self.start_time)
layout.addWidget(QLabel("Захват солнца:"))
self.sun_capture = QLineEdit("Захват солнца")
layout.addWidget(self.sun_capture)
btn_cancel = QPushButton("Отмена")
btn_cancel.clicked.connect(self.close)
layout.addWidget(btn_cancel)
btn_save = QPushButton("Сохранить PDF")
layout.addWidget(btn_save)
btn_send = QPushButton("Отправить")
layout.addWidget(btn_send)