from PyQt5.QtWidgets import QDialog, QLineEdit, QPushButton, QVBoxLayout, QLabel, QComboBox
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogObject(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Расчет объекта:"))
layout.addWidget(QLabel("MMSI:"))
self.mmsi = QLineEdit()
layout.addWidget(self.mmsi)
layout.addWidget(QLabel("IMO:"))
self.imo = QLineEdit()
layout.addWidget(self.imo)
layout.addWidget(QLabel("Порт приписки:"))
self.port = QLineEdit()
layout.addWidget(self.port)
layout.addWidget(QLabel("Н-борт:"))
self.n_board = QLineEdit()
layout.addWidget(self.n_board)
layout.addWidget(QLabel("Авиационное оборудование"))
self.aviation = QComboBox()
self.aviation.addItem("Выбрать")
layout.addWidget(self.aviation)
layout.addWidget(QLabel("Цвет корпуса:"))
self.color = QLineEdit()
layout.addWidget(self.color)
layout.addWidget(QLabel("Запас топлива на борту:"))
self.fuel = QLineEdit()
layout.addWidget(self.fuel)
layout.addWidget(QLabel("Место посадки на борт:"))
self.boarding = QLineEdit()
layout.addWidget(self.boarding)
layout.addWidget(QLabel("Контакты экипажа:"))
self.contacts = QLineEdit()
layout.addWidget(self.contacts)
layout.addWidget(QLabel("Владельцы:"))
self.owners = QLineEdit()
self.owners.setText("Число: Тип: Телефон: Адрес:")
layout.addWidget(self.owners)
layout.addWidget(QLabel("Оператор:"))
self.operator = QLineEdit()
layout.addWidget(self.operator)
layout.addWidget(QLabel("Число ПВО:"))
self.pvo = QLineEdit()
layout.addWidget(self.pvo)
layout.addWidget(QLabel("Телефон:"))
self.phone = QLineEdit()
layout.addWidget(self.phone)
layout.addWidget(QLabel("Адрес:"))
self.address = QLineEdit()
layout.addWidget(self.address)
btn_cancel = QPushButton("Отмена")
btn_cancel.clicked.connect(self.close)
layout.addWidget(btn_cancel)
btn_save = QPushButton("Сохранить PDF")
layout.addWidget(btn_save)
btn_send = QPushButton("Отправить")
layout.addWidget(btn_send)