from PyQt5.QtWidgets import QDialog, QDoubleSpinBox, QSpinBox, QPushButton, QVBoxLayout, QLabel
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogDriftParams(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Расчет дрейфа:"))
layout.addWidget(QLabel("Тип объекта:"))
self.object_type = QComboBox()
self.object_type.addItems(["Морское течение", "Ветер"])
layout.addWidget(self.object_type)
layout.addWidget(QLabel("Скорость (узлы):"))
self.speed = QDoubleSpinBox(minimum=0, value=1.0)
layout.addWidget(self.speed)
layout.addWidget(QLabel("Направление (градусы):"))
self.dir = QSpinBox(minimum=0, maximum=360, value=20)
layout.addWidget(self.dir)
layout.addWidget(QLabel("Время происшествия UTC:"))
self.incident_time = QDateTimeEdit()
self.incident_time.setDateTime(QDateTime.fromString("22 июня 2025 г. 21:02", "dd MMMM yyyy g. hh:mm"))
layout.addWidget(self.incident_time)
layout.addWidget(QLabel("Число лиц в опасности:"))
self.num_people = QSpinBox(minimum=0, value=0)
layout.addWidget(self.num_people)
layout.addWidget(QLabel("Требуемая помощь:"))
self.help_needed = QLineEdit()
layout.addWidget(self.help_needed)
btn_cancel = QPushButton("Отмена")
btn_cancel.clicked.connect(self.close)
layout.addWidget(btn_cancel)
btn_save = QPushButton("Сохранить PDF")
layout.addWidget(btn_save)
btn_send = QPushButton("Отправить")
layout.addWidget(btn_send)