from PyQt5.QtWidgets import QDialog, QDoubleSpinBox, QSpinBox, QPushButton, QVBoxLayout, QLabel
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogDriftCalc(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Расчет дрейфа:"))
layout.addWidget(QLabel("Объект АС / УС:"))
self.object_type = QLineEdit("Название")
layout.addWidget(self.object_type)
layout.addWidget(QLabel("Координаты:"))
self.coords = QLineEdit("33 * 0.0 * С.Ш.")
layout.addWidget(self.coords)
layout.addWidget(QLabel("Ситуация:"))
self.situation = QLineEdit()
layout.addWidget(self.situation)
layout.addWidget(QLabel("Источник информации:"))
self.source = QLineEdit("Время происшествия UTC: 22 июня 2025 г. 21:02")
layout.addWidget(self.source)
layout.addWidget(QLabel("Дополнительно:"))
self.additional = QLineEdit()
layout.addWidget(self.additional)
layout.addWidget(QLabel("Число лиц в опасности:"))
self.num_people = QSpinBox(minimum=0, value=0)
layout.addWidget(self.num_people)
layout.addWidget(QLabel("Требуемая помощь:"))
self.help_needed = QLineEdit()
layout.addWidget(self.help_needed)
btn_cancel = QPushButton("Отмена")
btn_cancel.clicked.connect(self.close)
layout.addWidget(btn_cancel)
btn_save = QPushButton("Сохранить PDF")
layout.addWidget(btn_save)
btn_send = QPushButton("Отправить")
layout.addWidget(btn_send)