from PyQt5.QtWidgets import QDialog, QDoubleSpinBox, QSpinBox, QPushButton, QVBoxLayout, QLabel
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogASWCalc(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Расчет ASW:"))
layout.addWidget(QLabel("Период действия:"))
self.from_time = QDateTimeEdit()
self.from_time.setDateTime(QDateTime.fromString("22.07.25 21:02", "dd.MM.yy hh:mm"))
layout.addWidget(self.from_time)
layout.addWidget(QLabel("По:"))
self.to_time = QDateTimeEdit()
self.to_time.setDateTime(QDateTime.fromString("23.07.25 10:02", "dd.MM.yy hh:mm"))
layout.addWidget(self.to_time)
layout.addWidget(QLabel("Скорость (узлы):"))
self.speed = QDoubleSpinBox(minimum=0, value=38.9)
layout.addWidget(self.speed)
layout.addWidget(QLabel("Направление (градусы):"))
self.dir = QSpinBox(minimum=0, maximum=360, value=90)
layout.addWidget(self.dir)
layout.addWidget(QLabel("Суммарный ветровой ветер:"))
self.wind_sum = QDoubleSpinBox(minimum=0, value=0.3)
layout.addWidget(self.wind_sum)
layout.addWidget(QLabel("Направление (градусы):"))
self.wind_dir = QSpinBox(minimum=0, maximum=360, value=0)
layout.addWidget(self.wind_dir)
layout.addWidget(QLabel("Ветровой фактор ASW:"))
self.asw_factor = QDoubleSpinBox(minimum=0, value=5.0)
layout.addWidget(self.asw_factor)
layout.addWidget(QLabel("Ветровой фактор ASWDe:"))
self.aswde_factor = QDoubleSpinBox(minimum=0, value=0.3)
layout.addWidget(self.aswde_factor)
layout.addWidget(QLabel("Ветровой фактор ASWD:"))
self.aswd_factor = QDoubleSpinBox(minimum=0, value=0.42)
layout.addWidget(self.aswd_factor)
btn_cancel = QPushButton("Отмена")
btn_cancel.clicked.connect(self.close)
layout.addWidget(btn_cancel)
btn_save = QPushButton("Сохранить PDF")
layout.addWidget(btn_save)
btn_send = QPushButton("Отправить")
layout.addWidget(btn_send)