from PyQt5.QtWidgets import QDialog, QDoubleSpinBox, QSpinBox, QPushButton, QVBoxLayout, QLabel, QMessageBox
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogDrift(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Расчет суммарного воздействия:"))
layout.addWidget(QLabel("Суммарное воздействие (м/с):"))
self.total_speed = QDoubleSpinBox(minimum=0, value=1.0)
layout.addWidget(self.total_speed)
layout.addWidget(QLabel("Направление (градусы):"))
self.total_dir = QSpinBox(minimum=0, maximum=360, value=20)
layout.addWidget(self.total_dir)
layout.addWidget(QLabel("Ветер:"))
self.wind_speed = QDoubleSpinBox(minimum=0, value=1.0)
layout.addWidget(self.wind_speed)
layout.addWidget(QLabel("Течение:"))
self.current_speed = QDoubleSpinBox(minimum=0, value=0.5)
layout.addWidget(self.current_speed)
layout.addWidget(QLabel("Температура воды °C:"))
self.water_temp = QDoubleSpinBox(minimum=-10, maximum=40, value=0.52)
layout.addWidget(self.water_temp)
layout.addWidget(QLabel("Источник потоков:"))
self.source = QLineEdit("Источник потоков")
layout.addWidget(self.source)
layout.addWidget(QLabel("Время происшествия UTC:"))
self.incident_time = QDateTimeEdit()
self.incident_time.setDateTime(QDateTime.fromString("22 июня 2025 г.", "dd MMMM yyyy g."))
layout.addWidget(self.incident_time)
layout.addWidget(QLabel("Число лиц в опасности:"))
self.num_people = QSpinBox(minimum=0, value=0)
layout.addWidget(self.num_people)
layout.addWidget(QLabel("Требуемая помощь:"))
self.help_needed = QLineEdit()
layout.addWidget(self.help_needed)
btn = QPushButton("Отмена")
btn.clicked.connect(self.close)
layout.addWidget(btn)
btn_save = QPushButton("Сохранить PDF")
layout.addWidget(btn_save)
btn_send = QPushButton("Отправить")
layout.addWidget(btn_send)