from PyQt5.QtWidgets import QDialog, QDoubleSpinBox, QSpinBox, QPushButton, QVBoxLayout, QLabel
from PyQt5.QtCore import QDateTime, QDateTimeEdit
class DialogDatumCalc(QDialog):
def __init__(self, parent=None):
super().__init__(parent)
layout = QVBoxLayout(self)
layout.addWidget(QLabel("Расчет datum:"))
layout.addWidget(QLabel("LKP (lon,lat):"))
self.lkp = QLineEdit("30.0,60.0")
layout.addWidget(self.lkp)
layout.addWidget(QLabel("Wind speed:"))
self.wind_speed = QDoubleSpinBox(minimum=0, value=10.0)
layout.addWidget(self.wind_speed)
layout.addWidget(QLabel("Wind dir:"))
self.wind_dir = QSpinBox(minimum=0, maximum=360, value=0)
layout.addWidget(self.wind_dir)
layout.addWidget(QLabel("Current speed:"))
self.current_speed = QDoubleSpinBox(minimum=0, value=2.0)
layout.addWidget(self.current_speed)
layout.addWidget(QLabel("Current dir:"))
self.current_dir = QSpinBox(minimum=0, maximum=360, value=90)
layout.addWidget(self.current_dir)
layout.addWidget(QLabel("Time (hours):"))
self.time_hours = QDoubleSpinBox(minimum=0, value=3.0)
layout.addWidget(self.time_hours)
btn = QPushButton("Calculate")
btn.clicked.connect(self.calculate)
layout.addWidget(btn)
def calculate(self):
self.accept()